#!/usr/bin/env node
// @ts-check
'use strict';

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const COMMIT_SEPARATOR = '\u001e';
const FIELD_SEPARATOR = '\u001f';

/** @typedef {'dry-run' | 'prepare' | 'create' | 'update'} Mode */
/** @typedef {'major' | 'minor' | 'patch'} Bump */
/** @typedef {{ type: string, section?: string, hidden?: true, bump?: Bump }} TypeConfig */
/** @typedef {{ hash: string, shortHash: string, header: string, type?: string, subject: string, body: string, breaking: boolean }} Commit */
/** @typedef {{ version: string, releaseNotes: string }} DeliveryPlan */
/** @typedef {{ kind: 'release', release: DeliveryPlan } | { kind: 'non-release' }} PullRequestPlan */
/** @typedef {{ getCurrentBranch: () => string, getCommitsFromBase: (options: { baseRef: string, headRef: string }) => string | Commit[], requireCleanWorkingTree: () => void, requireBranchUpToDateWithMain: () => void, removeReleaseCommit: () => void, commitVersionBump: (version: string) => void, pushBranch: (branch: string) => void, forcePushBranch: (branch: string) => void }} GitAdapter */
/** @typedef {{ requirePullRequestExists: (branch: string) => void, createPullRequest: (options: { branch: string, title: string, body: string }) => void }} GitHubAdapter */
/** @typedef {{ readPackageJson: () => { version: string, [key: string]: unknown }, writePackageJson: (packageJson: { version: string, [key: string]: unknown }) => void, readChangelog: () => string, writeChangelog: (changelog: string) => void }} FilesAdapter */
/** @typedef {{ git: GitAdapter, github: GitHubAdapter, files: FilesAdapter, now: () => Date, log: (...messages: string[]) => void }} Context */
/** @typedef {(command: string, args: string[], options: { cwd: string }) => string} RunCommand */
/** @typedef {(file: string, data: string) => void} WriteFile */
/** @typedef {(file: string, encoding: 'utf8') => string} ReadFile */

/** @type {TypeConfig[]} */
const TYPES = [
	{ type: 'behav', section: 'New Behaviors', bump: 'minor' },
	{ type: 'behavfix', section: 'Bug Fixes', bump: 'patch' },
	{ type: 'perf', section: 'Performance Improvements', bump: 'patch' },
	{ type: 'perffix', section: 'Performance Improvements', bump: 'patch' },
	{ type: 'docs', section: 'Documentation', bump: 'patch' },
	{ type: 'refac', hidden: true, bump: undefined },
	{ type: 'test', hidden: true, bump: undefined },
	{ type: 'style', hidden: true, bump: undefined },
	{ type: 'chore', hidden: true, bump: undefined },
	{ type: 'cicd', hidden: true, bump: undefined },
];

const TYPE_CONFIG = new Map(TYPES.map((config) => [config.type, config]));
const BUMP_PRIORITY = new Map([
	['patch', 1],
	['minor', 2],
	['major', 3],
]);

/**
 * Parses the pull-request CLI mode from user-provided arguments.
 *
 * Use this at the command boundary only. It intentionally accepts exactly one
 * mode flag; callers should pass raw CLI arguments without `node` or script
 * path entries.
 *
 * @param {string[]} args
 * @returns {{ mode: Mode }}
 */
function parseArgs(args) {
	/** @type {Set<Mode>} */
	const flags = new Set();

	for (const arg of args) {
		if (arg === '--dry-run') flags.add('dry-run');
		else if (arg === '--prepare' || arg === '-p') flags.add('prepare');
		else if (arg === '--create' || arg === '-c') flags.add('create');
		else if (arg === '--update') flags.add('update');
		else throw new Error(`Unknown option: ${arg}`);
	}

	if (flags.size > 1) {
		throw new Error('Cannot combine pull-request mode options.');
	}

	const [mode] = flags;
	return { mode: mode || 'create' };
}

/**
 * Converts machine-formatted `git log` output into commit objects used by note
 * generation.
 *
 * The input must use this script's record and field separators. Use it with
 * `git log --format` output generated by the git adapter; it is not a general
 * parser for human-readable git logs.
 *
 * @param {string} output
 * @returns {Commit[]}
 */
function parseCommitLog(output) {
	return output
		.split(COMMIT_SEPARATOR)
		.filter(Boolean)
		.map((record) => {
			const [hash = '', header = '', ...bodyParts] =
				record.split(FIELD_SEPARATOR);
			const body = bodyParts.join(FIELD_SEPARATOR).trim();
			const parsedHeader = parseHeader(header.trim());

			return {
				hash: hash.trim(),
				shortHash: hash.trim().slice(0, 7),
				header: header.trim(),
				type: parsedHeader.type,
				subject: parsedHeader.subject,
				body,
				breaking:
					parsedHeader.breaking ||
					body.split(/\r?\n/).some((line) => /^BREAKING-CHANGE: .+/.test(line)),
			};
		});
}

/**
 * @param {string} header
 * @returns {{ type?: string, subject: string, breaking: boolean }}
 */
function parseHeader(header) {
	const match = /^([a-z]+)(?:\([^)]+\))?(!)?: (.+)$/.exec(header);

	return {
		type: match ? match[1] : undefined,
		subject: match ? match[3] : header,
		breaking: Boolean(match && match[2]),
	};
}

/**
 * Computes the next version and changelog entry for a set of parsed commits.
 *
 * Use this for deterministic note generation after commits have already been
 * collected and parsed. It throws when the commit range contains no
 * bump-worthy commits.
 *
 * @param {{ baseVersion: string, commits: Commit[], date: string }} options
 * @returns {DeliveryPlan}
 */
function generateReleasePlan({ baseVersion, commits, date }) {
	const bump = getRequiredBump(commits);
	if (!bump) {
		throw new Error('No bump-worthy commits found.');
	}

	const version = incrementVersion(baseVersion, bump);
	const releaseNotes = renderReleaseNotes({ version, commits, date });

	return { version, releaseNotes };
}

/**
 * @param {Commit[]} commits
 * @returns {Bump | null}
 */
function getRequiredBump(commits) {
	/** @type {Bump | undefined} */
	let selected;

	for (const commit of commits) {
		const configuredBump = commit.breaking
			? 'major'
			: TYPE_CONFIG.get(commit.type || '')?.bump;

		if (
			configuredBump &&
			(!selected ||
				(BUMP_PRIORITY.get(configuredBump) || 0) >
					(BUMP_PRIORITY.get(selected) || 0))
		) {
			selected = configuredBump;
		}
	}

	return selected || null;
}

/**
 * Applies a SemVer bump to a plain `X.Y.Z` version string.
 *
 * Use this for release versions only; prerelease/build metadata and forced
 * version overrides are intentionally outside this script's contract.
 *
 * @param {string} version
 * @param {Bump} bump
 * @returns {string}
 */
function incrementVersion(version, bump) {
	const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
	if (!match) throw new Error(`Invalid SemVer version: ${version}`);

	const major = Number(match[1]);
	const minor = Number(match[2]);
	const patch = Number(match[3]);

	if (bump === 'major') return `${major + 1}.0.0`;
	if (bump === 'minor') return `${major}.${minor + 1}.0`;
	return `${major}.${minor}.${patch + 1}`;
}

/**
 * @param {{ version: string, commits: Commit[], date: string }} options
 * @returns {string}
 */
function renderReleaseNotes({ version, commits, date }) {
	const sections = getReleaseNoteSections(commits).map(
		(section) =>
			`### ${section.title}\n\n` +
			section.commits
				.map((commit) => `- ${commit.subject} (${commit.shortHash})`)
				.join('\n'),
	);

	return `## [${version}] - ${date}\n\n${sections.join('\n\n')}\n`;
}

/**
 * @param {Commit[]} commits
 * @returns {{ title: string, commits: Commit[] }[]}
 */
function getReleaseNoteSections(commits) {
	/** @type {{ title: string, commits: Commit[] }[]} */
	const sections = [];

	const breakingCommits = commits.filter((commit) => commit.breaking);
	if (breakingCommits.length > 0) {
		sections.push({ title: 'Breaking Changes', commits: breakingCommits });
	}

	/** @type {Map<string, Commit[]>} */
	const commitsBySection = new Map();
	const sectionTitles = [];

	for (const config of TYPES) {
		if (!config.section) continue;
		if (!commitsBySection.has(config.section)) {
			commitsBySection.set(config.section, []);
			sectionTitles.push(config.section);
		}

		commitsBySection
			.get(config.section)
			?.push(...commits.filter((commit) => commit.type === config.type));
	}

	for (const title of sectionTitles) {
		const sectionCommits = commitsBySection.get(title) || [];
		if (sectionCommits.length > 0) {
			sections.push({ title, commits: sectionCommits });
		}
	}

	return sections;
}

/**
 * Creates a workflow context from production adapters.
 *
 * Supply adapters in tests to observe domain effects without shell command
 * planning. When omitted, the context uses the local repository, filesystem,
 * and GitHub CLI.
 *
 * @param {{ git?: GitAdapter, github?: GitHubAdapter, files?: FilesAdapter, cwd?: string, runCommand?: RunCommand, writeFile?: WriteFile, readFile?: ReadFile, now?: () => Date, log?: (...messages: string[]) => void }} [deps]
 * @returns {Context}
 */
function createContext({
	git,
	github,
	files,
	cwd = process.cwd(),
	runCommand = execCommand,
	writeFile = writeTextFile,
	readFile = readTextFile,
	now = () => new Date(),
	log = console.log,
} = {}) {
	return {
		git: git || createGitAdapter({ cwd, runCommand }),
		github: github || createGitHubAdapter({ cwd, runCommand }),
		files: files || createFilesAdapter({ cwd, readFile, writeFile }),
		now,
		log,
	};
}

/**
 * Computes and prints the next version and generated notes without side effects.
 *
 * Use this for `--dry-run` and for tests that need to verify planning behavior
 * through adapters rather than shell command arrays.
 *
 * @param {Context} context
 * @returns {DeliveryPlan | null}
 */
function preview(context) {
	const planned = planDelivery(context);
	if (planned.kind === 'non-release') {
		context.log(
			'No release required: commit range contains no bump-worthy commits.',
		);
		return null;
	}

	context.log(`Next version: ${planned.release.version}`);
	context.log('');
	context.log(planned.release.releaseNotes.trimEnd());

	return planned.release;
}

/**
 * Updates package/changelog files and creates the local bump commit.
 *
 * This requires a clean working tree before computing changes. It does not push
 * or open a GitHub pull request.
 *
 * @param {Context} context
 * @returns {DeliveryPlan | null}
 */
function prepare(context) {
	context.git.requireCleanWorkingTree();

	const planned = planDelivery(context);
	if (planned.kind === 'non-release') {
		context.log(
			'No release required: skipping package version, changelog, and release commit.',
		);
		return null;
	}

	const packageJson = context.files.readPackageJson();
	packageJson.version = planned.release.version;
	context.files.writePackageJson(packageJson);
	context.files.writeChangelog(
		writeReleaseNotes(
			context.files.readChangelog(),
			planned.release.releaseNotes,
		),
	);
	context.git.commitVersionBump(planned.release.version);

	return planned.release;
}

/**
 * Prepares the branch, pushes it, and opens a GitHub PR to `main`.
 *
 * Use this for the default CLI mode. The pull request title is the same
 * version-bump subject used for the local commit, and the body is the generated
 * release notes.
 *
 * @param {Context} context
 * @returns {DeliveryPlan | null}
 */
function create(context) {
	const release = prepare(context);
	const branch = context.git.getCurrentBranch();
	const title = release
		? `chore(release): ${release.version}`
		: 'chore: non-release changes';
	const body = release
		? release.releaseNotes
		: renderNonReleasePullRequestBody();

	context.git.pushBranch(branch);
	context.github.createPullRequest({
		branch,
		title,
		body,
	});

	return release;
}

/**
 * Replaces an existing PR branch's generated release commit and force-pushes it.
 *
 * Use this after new commits are added or after rebasing an already-open PR
 * branch. The workflow requires an existing pull request so first-time branches
 * keep using `create`.
 *
 * @param {Context} context
 * @returns {DeliveryPlan | null}
 */
function update(context) {
	context.git.requireCleanWorkingTree();

	const branch = context.git.getCurrentBranch();
	context.github.requirePullRequestExists(branch);
	context.git.requireBranchUpToDateWithMain();
	context.git.removeReleaseCommit();

	const release = prepare(context);
	context.git.forcePushBranch(branch);

	return release;
}

/**
 * @returns {string}
 */
function renderNonReleasePullRequestBody() {
	return [
		'## Non-Release Pull Request',
		'',
		'No package version bump is required for this commit range.',
		'',
		'This PR contains only hidden non-breaking changes, so it has no changelog entry and no release artifact.',
	].join('\n');
}

/**
 * Inserts generated notes into an existing changelog.
 *
 * The new entry is inserted before the first existing release heading while
 * preserving the changelog preamble.
 *
 * @param {string} changelog
 * @param {string} releaseNotes
 * @returns {string}
 */
function writeReleaseNotes(changelog, releaseNotes) {
	const lines = changelog.split(/\r?\n/);
	let insertAt = lines.length;

	for (let index = 1; index < lines.length; index++) {
		if (lines[index].startsWith('## ')) {
			insertAt = index;
			break;
		}
	}

	while (insertAt > 0 && lines[insertAt - 1] === '') insertAt--;

	const before = lines.slice(0, insertAt).join('\n').trimEnd();
	const after = lines.slice(insertAt).join('\n').trimStart();

	return `${before}\n\n${releaseNotes.trimEnd()}${after ? `\n\n${after}` : ''}\n`;
}

/**
 * Runs the pull-request workflow from CLI arguments.
 *
 * @param {{ args?: string[], cwd?: string, runCommand?: RunCommand, writeFile?: WriteFile, readFile?: ReadFile, now?: () => Date, log?: (...messages: string[]) => void }} [options]
 * @returns {DeliveryPlan | null}
 */
function runCli({
	args = process.argv.slice(2),
	cwd = process.cwd(),
	runCommand = execCommand,
	writeFile = writeTextFile,
	readFile = readTextFile,
	now = () => new Date(),
	log = console.log,
} = {}) {
	const { mode } = parseArgs(args);
	const context = createContext({
		cwd,
		runCommand,
		writeFile,
		readFile,
		now,
		log,
	});

	if (mode === 'dry-run') return preview(context);
	if (mode === 'prepare') return prepare(context);
	if (mode === 'update') return update(context);
	return create(context);
}

/**
 * @param {Context} context
 * @param {{ baseRef: string, headRef: string }} [commitRange]
 * @param {string} [baseVersion]
 * @returns {PullRequestPlan}
 */
function planDelivery(context, commitRange, baseVersion) {
	const resolvedBaseVersion =
		baseVersion || context.files.readPackageJson().version;
	const commits = getCommits(context, commitRange);

	if (!getRequiredBump(commits)) {
		return { kind: 'non-release' };
	}

	return {
		kind: 'release',
		release: generateReleasePlan({
			baseVersion: resolvedBaseVersion,
			commits,
			date: context.now().toISOString().slice(0, 10),
		}),
	};
}

/**
 * @param {Context} context
 * @param {{ baseRef: string, headRef: string }} [range]
 * @returns {Commit[]}
 */
function getCommits(context, range) {
	const resolvedRange = range || {
		baseRef: 'main',
		headRef: context.git.getCurrentBranch(),
	};

	return normalizeCommits(context.git.getCommitsFromBase(resolvedRange));
}

/**
 * @param {string | Commit[]} commits
 * @returns {Commit[]}
 */
function normalizeCommits(commits) {
	return typeof commits === 'string' ? parseCommitLog(commits) : commits;
}

/**
 * @param {{ cwd: string, runCommand: RunCommand }} options
 * @returns {GitAdapter}
 */
function createGitAdapter({ cwd, runCommand }) {
	return {
		getCurrentBranch() {
			const branchName = runCommand('git', ['branch', '--show-current'], {
				cwd,
			}).trim();

			if (!branchName)
				throw new Error('Cannot create a PR without a current branch.');
			return branchName;
		},
		getCommitsFromBase({ baseRef, headRef }) {
			return runCommand(
				'git',
				[
					'log',
					`${baseRef}..${headRef}`,
					`--format=${COMMIT_SEPARATOR}%H${FIELD_SEPARATOR}%s${FIELD_SEPARATOR}%b`,
				],
				{ cwd },
			);
		},
		requireCleanWorkingTree() {
			const status = runCommand('git', ['status', '--porcelain'], {
				cwd,
			}).trim();
			if (status) {
				throw new Error(
					'Working tree must be clean before running PR tooling.',
				);
			}
		},
		requireBranchUpToDateWithMain() {
			const branchBase = runCommand('git', ['merge-base', 'main', 'HEAD'], {
				cwd,
			}).trim();
			const mainHead = runCommand('git', ['rev-parse', 'main'], {
				cwd,
			}).trim();

			if (branchBase !== mainHead) {
				throw new Error(
					'Branch must be rebased on top of main before updating the PR.',
				);
			}
		},
		removeReleaseCommit() {
			const releaseCommits = findBranchReleaseCommits();

			if (releaseCommits.length === 0) return;
			if (releaseCommits.length > 1) {
				throw new Error(
					`Cannot update PR with multiple branch-local release commits: ${releaseCommits.map((commit) => commit.hash).join(', ')}`,
				);
			}

			const [{ hash }] = releaseCommits;
			runCommand('git', ['rebase', '--onto', `${hash}^`, hash, 'HEAD'], {
				cwd,
			});
		},
		commitVersionBump(version) {
			runCommand('git', ['add', 'package.json', 'CHANGELOG.md'], { cwd });
			runCommand('git', ['commit', '-m', `chore(release): ${version}`], {
				cwd,
			});
		},
		pushBranch(branch) {
			runCommand('git', ['push', '-u', 'origin', branch], { cwd });
		},
		forcePushBranch(branch) {
			runCommand('git', ['push', '--force-with-lease', 'origin', branch], {
				cwd,
			});
		},
	};

	/**
	 * @returns {{ hash: string, subject: string }[]}
	 */
	function findBranchReleaseCommits() {
		const output = runCommand(
			'git',
			[
				'log',
				'main..HEAD',
				'--not',
				'origin/main',
				`--format=%H${FIELD_SEPARATOR}%s`,
			],
			{ cwd },
		).trim();

		if (!output) return [];

		return output
			.split(/\r?\n/)
			.map((line) => {
				const [hash = '', subject = ''] = line.split(FIELD_SEPARATOR);
				return { hash, subject };
			})
			.filter((commit) =>
				/^chore\(release\): \d+\.\d+\.\d+$/.test(commit.subject),
			);
	}
}

/**
 * @param {{ cwd: string, runCommand: RunCommand }} options
 * @returns {GitHubAdapter}
 */
function createGitHubAdapter({ cwd, runCommand }) {
	return {
		requirePullRequestExists(branch) {
			const count = runCommand(
				'gh',
				['pr', 'list', '--head', branch, '--json', 'number', '--jq', 'length'],
				{ cwd },
			).trim();

			if (count === '0') {
				throw new Error(
					`No pull request exists for ${branch}. Run npm run pr:create first.`,
				);
			}
		},
		createPullRequest({ branch, title, body }) {
			runCommand(
				'gh',
				[
					'pr',
					'create',
					'--base',
					'main',
					'--head',
					branch,
					'--title',
					title,
					'--body',
					body,
				],
				{ cwd },
			);
		},
	};
}

/**
 * @param {{ cwd: string, readFile: ReadFile, writeFile: WriteFile }} options
 * @returns {FilesAdapter}
 */
function createFilesAdapter({ cwd, readFile, writeFile }) {
	const packageJsonPath = path.join(cwd, 'package.json');
	const changelogPath = path.join(cwd, 'CHANGELOG.md');

	return {
		readPackageJson() {
			return JSON.parse(readFile(packageJsonPath, 'utf8'));
		},
		writePackageJson(packageJson) {
			writeFile(
				packageJsonPath,
				`${JSON.stringify(packageJson, null, '\t')}\n`,
			);
		},
		readChangelog() {
			return readFile(changelogPath, 'utf8');
		},
		writeChangelog(changelog) {
			writeFile(changelogPath, changelog);
		},
	};
}

/**
 * @param {string} command
 * @param {string[]} args
 * @param {{ cwd: string }} options
 * @returns {string}
 */
function execCommand(command, args, options) {
	return execFileSync(command, args, {
		...options,
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'inherit'],
	});
}

/** @type {WriteFile} */
function writeTextFile(file, data) {
	fs.writeFileSync(file, data);
}

/** @type {ReadFile} */
function readTextFile(file, encoding) {
	return fs.readFileSync(file, encoding);
}

if (require.main === module) {
	try {
		runCli();
	} catch (error) {
		console.error(error instanceof Error ? error.message : String(error));
		process.exit(1);
	}
}

module.exports = {
	parseArgs,
	createContext,
	preview,
	prepare,
	create,
	update,
	planDelivery,
	parseCommitLog,
	getRequiredBump,
	generateReleasePlan,
	writeReleaseNotes,
	runCli,
};
